/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author cindy
 */
public class PanelCompras extends javax.swing.JPanel {

    /**
     * Creates new form PanelCompras
     */
    public PanelCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        separador = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtFechaCompra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtIdCuentaCobro1 = new javax.swing.JTextField();
        txtIdProveedor = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        txtTotalBruto = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        cmbMetodoPago = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JPanel();
        agregar = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        actualizar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        eliminar = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(28, 95, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Fecha de Compra:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 160, -1));

        txtFechaCompra.setBackground(new java.awt.Color(75, 128, 146));
        txtFechaCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFechaCompra.setForeground(new java.awt.Color(255, 255, 255));
        txtFechaCompra.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtFechaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 230, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("ID Compra:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 160, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("ID Proveedor:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 160, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Fecha:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 160, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Documento:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 160, -1));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Total Bruto:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, -1));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Forma de Pago:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 120, -1));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Estado:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 100, -1));

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("ID Usuario:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 160, -1));

        txtIdCuentaCobro1.setBackground(new java.awt.Color(75, 128, 146));
        txtIdCuentaCobro1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdCuentaCobro1.setForeground(new java.awt.Color(255, 255, 255));
        txtIdCuentaCobro1.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdCuentaCobro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 290, -1));

        txtIdProveedor.setBackground(new java.awt.Color(75, 128, 146));
        txtIdProveedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdProveedor.setForeground(new java.awt.Color(255, 255, 255));
        txtIdProveedor.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 290, -1));

        txtFecha.setBackground(new java.awt.Color(75, 128, 146));
        txtFecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 160, -1));

        txtDocumento.setBackground(new java.awt.Color(75, 128, 146));
        txtDocumento.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtDocumento.setForeground(new java.awt.Color(255, 255, 255));
        txtDocumento.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 430, -1));

        txtTotalBruto.setBackground(new java.awt.Color(75, 128, 146));
        txtTotalBruto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtTotalBruto.setForeground(new java.awt.Color(255, 255, 255));
        txtTotalBruto.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtTotalBruto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 190, -1));

        txtEstado.setBackground(new java.awt.Color(75, 128, 146));
        txtEstado.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(255, 255, 255));
        txtEstado.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 140, -1));

        txtIdUsuario.setBackground(new java.awt.Color(75, 128, 146));
        txtIdUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtIdUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 280, -1));

        cmbMetodoPago.setBackground(new java.awt.Color(75, 128, 146));
        cmbMetodoPago.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cmbMetodoPago.setForeground(new java.awt.Color(255, 255, 255));
        cmbMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Otro Método" }));
        cmbMetodoPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbMetodoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMetodoPagoActionPerformed(evt);
            }
        });
        add(cmbMetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, 100, -1));

        btnAgregar.setBackground(new java.awt.Color(75, 128, 146));
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        agregar.setText("Agregar");
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 90, 30));

        btnActualizar.setBackground(new java.awt.Color(75, 128, 146));
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        actualizar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        actualizar.setForeground(new java.awt.Color(255, 255, 255));
        actualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        actualizar.setText("Actualizar");
        actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 90, 30));

        btnEliminar.setBackground(new java.awt.Color(75, 128, 146));
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        eliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        eliminar.setForeground(new java.awt.Color(255, 255, 255));
        eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminar.setText("Eliminar");
        eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 530, 90, 30));

        btnBuscar.setBackground(new java.awt.Color(75, 128, 146));
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Buscar");
        btnBuscar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 90, 30));

        titulo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("COMPRAS");
        add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 850, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void cmbMetodoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMetodoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMetodoPagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel actualizar;
    public javax.swing.JLabel agregar;
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnAgregar;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnSalir;
    public javax.swing.JComboBox<String> cmbMetodoPago;
    private javax.swing.JLabel eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo1;
    public javax.swing.JTextField txtDocumento;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtFechaCompra;
    public javax.swing.JTextField txtIdCuentaCobro1;
    public javax.swing.JTextField txtIdProveedor;
    public javax.swing.JTextField txtIdUsuario;
    public javax.swing.JTextField txtTotalBruto;
    // End of variables declaration//GEN-END:variables
}
