/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

/**
 *
 * @author cindy
 */
public class PanelAuditoria extends javax.swing.JPanel {

    /**
     * Creates new form PanelAuditoria
     */
    public PanelAuditoria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        marcaAgua = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        separador = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdAuditoria = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtTipoCambio = new javax.swing.JTextField();
        txtIdRegistro = new javax.swing.JTextField();
        txtOperacion = new javax.swing.JTextField();
        txtIdUsuario = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(28, 95, 118));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("AUDITORÍA");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 850, -1));

        btnSalir.setBackground(new java.awt.Color(75, 128, 146));
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 30, 30));

        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 30, 30));

        marcaAgua.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        marcaAgua.setForeground(new java.awt.Color(255, 255, 255));
        marcaAgua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        marcaAgua.setText("FARMACIA");
        add(marcaAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 850, -1));

        separador2.setBackground(new java.awt.Color(255, 255, 255));
        separador2.setForeground(new java.awt.Color(255, 255, 255));
        add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 850, -1));

        separador.setBackground(new java.awt.Color(255, 255, 255));
        separador.setForeground(new java.awt.Color(255, 255, 255));
        add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 850, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("ID Auditoría:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, 20));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Fecha:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 140, 20));

        txtIdAuditoria.setBackground(new java.awt.Color(75, 128, 146));
        txtIdAuditoria.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdAuditoria.setForeground(new java.awt.Color(255, 255, 255));
        txtIdAuditoria.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdAuditoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 270, -1));

        txtFecha.setBackground(new java.awt.Color(75, 128, 146));
        txtFecha.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 270, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Tipo de Cambio:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 140, 20));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("ID Registro:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 140, 20));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Operacion:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 140, 20));

        jLabel13.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("ID Usuario:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 140, 20));

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Motivo:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 140, 20));

        txtTipoCambio.setBackground(new java.awt.Color(75, 128, 146));
        txtTipoCambio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtTipoCambio.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoCambio.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtTipoCambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 270, -1));

        txtIdRegistro.setBackground(new java.awt.Color(75, 128, 146));
        txtIdRegistro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdRegistro.setForeground(new java.awt.Color(255, 255, 255));
        txtIdRegistro.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 270, -1));

        txtOperacion.setBackground(new java.awt.Color(75, 128, 146));
        txtOperacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtOperacion.setForeground(new java.awt.Color(255, 255, 255));
        txtOperacion.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 270, -1));

        txtIdUsuario.setBackground(new java.awt.Color(75, 128, 146));
        txtIdUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtIdUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtIdUsuario.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 270, -1));

        txtMotivo.setBackground(new java.awt.Color(75, 128, 146));
        txtMotivo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtMotivo.setForeground(new java.awt.Color(255, 255, 255));
        txtMotivo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtMotivo.setCaretColor(new java.awt.Color(255, 255, 255));
        add(txtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 350, 80));

        btnAgregar.setBackground(new java.awt.Color(75, 128, 146));
        btnAgregar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Agregar");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 90, 30));

        btnActualizar.setBackground(new java.awt.Color(75, 128, 146));
        btnActualizar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnActualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Actualizar");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 90, 30));

        btnEliminar.setBackground(new java.awt.Color(75, 128, 146));
        btnEliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Eliminar");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 90, 30));

        btnBuscar.setBackground(new java.awt.Color(75, 128, 146));
        btnBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Buscar");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 90, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel btnActualizar;
    public javax.swing.JPanel btnAgregar;
    public javax.swing.JPanel btnBuscar;
    public javax.swing.JPanel btnEliminar;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel marcaAgua;
    private javax.swing.JSeparator separador;
    private javax.swing.JSeparator separador2;
    private javax.swing.JLabel titulo;
    public javax.swing.JTextField txtFecha;
    public javax.swing.JTextField txtIdAuditoria;
    public javax.swing.JTextField txtIdRegistro;
    public javax.swing.JTextField txtIdUsuario;
    public javax.swing.JTextField txtMotivo;
    public javax.swing.JTextField txtOperacion;
    public javax.swing.JTextField txtTipoCambio;
    // End of variables declaration//GEN-END:variables
}
